version: "3.8"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.78.1
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n  # Existing volume for n8n data
      - /Users/anshumohanacharya/Documents/Github/n8n-reachinbox/dist:/custom-nodes  # Mount custom nodes
    restart: unless-stopped
    environment:
      - N8N_CUSTOM_EXTENSIONS=/custom-nodes  # Load nodes from this path
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=n8n.outbox.vc
      - N8N_PORT=5678
      - N8N_DIAGNOSTICS_ENABLED=false  
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.outbox.vc
      - WEBHOOK_TUNNEL_URL=https://n8n.outbox.vc
      - N8N_EDITOR_BASE_URL=https://n8n.outbox.vc
      - VUE_APP_URL_BASE_API=https://n8n.outbox.vc
      # Fixes for current issues
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_TRUST_PROXY=true

      # Performance tuning
      - N8N_WS_RECONNECT_INTERVAL=5000
      - N8N_WS_MAX_RECONNECT_RETRIES=30
      - N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=true
    tty: true

volumes:
  n8n_data: